### ISSUE TITLE
Create UI/UX design for the website

### ISSUE THREAD

**Issue by Ank-22** [Ank221199/E-CommerceVueAndFlask#6]
## Expectation :
Some thing alone this: https://dribbble.com/shots/16899784-eCommerce-Homepage

**Comment by avezqureshi14** [comment]
Hello @Ank221199  I am ready to do this can you assign this to me you can checkout my UI related work here `https://avezqureshi.netlify.app/`

**Comment by Ank-22** [comment]
> Hello @Ank221199 I am ready to do this can you assign this to me you can checkout my UI related work here `https://avezqureshi.netlify.app/`

done

**Comment by Ank-22** [comment]
@avezqureshi14 , Saw your working, if you can, take up this task also. It would be much appreciated 

https://github.com/Ank221199/WorkoutGenerator/issues/6

**Comment by avezqureshi14** [comment]
Thank you @Ank221199 for assigning me this task, and also I will be happy to do second one too

**Comment by Ank-22** [comment]
@avezqureshi14 

Color palette: https://coolors.co/palette/2d87ac-5cc3ec-787878-343434-ffffff

**Comment by avezqureshi14** [comment]
> @avezqureshi14
> 
> Color palette: https://coolors.co/palette/2d87ac-5cc3ec-787878-343434-ffffff

OK Sir I will be using the same color combination 😊
